### ISSUE TITLE
need specific configuration information

### ISSUE THREAD

**Issue by hStormh** [stuart-thomas-zoopla/LlmQualityWithTrulens#1]
"Could you please provide the Python version and other environment configuration information required to run this file? Your response would be greatly appreciated, and it would be my honor to receive your reply."

**Comment by stuart-thomas-tqd** [comment]
You're best not running this code and instead checking out my blog posts about how to use trulens - https://www.thequalityduck.co.uk/testing-ai-how-to-assess-llm-quality-with-trulens/ and checking out their official documentation https://www.trulens.org/trulens_eval/getting_started/

To run it exactly as I did you will need to be running Ollama locally too, you can read some more about that here https://www.thequalityduck.co.uk/testing-ai-how-to-run-the-llama-2-large-language-model-locally/
